general:
  buildTool: 'docker'
  productiveBranch: 'dev'
  vaultPath: 'piper/PIPELINE-GROUP-70'
  vaultBasePath: 'piper/PIPELINE-GROUP-70'
  vaultPipelineName: 'mmt-devops-cpi-delivery'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
  Security:
    detectExecuteScan: true
  Release:
    sapDownloadArtifact: false
  Post:
    # Secret rotation handled by Hyperspace Portal, enabling it back might cause unintended behavior
    vaultRotateSecretId: false
steps:
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-70-default'
  kanikoExecute:
    containerImageName: 'mmt-devops-cpi-delivery'
  sapCumulusUpload:
    pipelineId: 'ab98df78-71b3-4696-94fb-5f33b9f70c39'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
  detectExecuteScan:
    serverUrl: https://sap.blackducksoftware.com
    groups: ['Delivery Orchestration for SAP Cloud Integration']

