// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Config struct {
	ID               int32  `db:"id" json:"id"`
	ConfigName       string `db:"config_name" json:"config_name"`
	Type             string `db:"type" json:"type"`
	AuthUrl          string `db:"auth_url" json:"auth_url"`
	ApiUrl           string `db:"api_url" json:"api_url"`
	AuthClientID     string `db:"auth_client_id" json:"auth_client_id"`
	AuthClientSecret string `db:"auth_client_secret" json:"auth_client_secret"`
}

type Group struct {
	ID        int32  `db:"id" json:"id"`
	GroupName string `db:"group_name" json:"group_name"`
}

type User struct {
	ID                int32              `db:"id" json:"id"`
	Username          string             `db:"username" json:"username"`
	HashedPassword    string             `db:"hashed_password" json:"hashed_password"`
	FullName          string             `db:"full_name" json:"full_name"`
	Email             string             `db:"email" json:"email"`
	PasswordChangedAt pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
