// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Config struct {
	ID               int    `db:"id" json:"id"`
	Name             string `db:"name" json:"name"`
	Type             string `db:"type" json:"type"`
	AuthUrl          string `db:"auth_url" json:"auth_url"`
	ApiUrl           string `db:"api_url" json:"api_url"`
	AuthClientID     string `db:"auth_client_id" json:"auth_client_id"`
	AuthClientSecret string `db:"auth_client_secret" json:"auth_client_secret"`
}

type Cpitmpl struct {
	ID            int      `db:"id" json:"id"`
	StepID        int      `db:"step_id" json:"step_id"`
	CpiConfigID   int      `db:"cpi_config_id" json:"cpi_config_id"`
	CpiPackageIds []string `db:"cpi_package_ids" json:"cpi_package_ids"`
	CpiIflowIds   []string `db:"cpi_iflow_ids" json:"cpi_iflow_ids"`
	CpiScriptIds  []string `db:"cpi_script_ids" json:"cpi_script_ids"`
	Status        string   `db:"status" json:"status"`
}

type Execution struct {
	ID     int    `db:"id" json:"id"`
	JobID  int    `db:"job_id" json:"job_id"`
	Status string `db:"status" json:"status"`
}

type Group struct {
	ID        int    `db:"id" json:"id"`
	GroupName string `db:"group_name" json:"group_name"`
}

type Job struct {
	ID     int    `db:"id" json:"id"`
	Name   string `db:"name" json:"name"`
	Steps  []int  `db:"steps" json:"steps"`
	Status string `db:"status" json:"status"`
}

type Step struct {
	ID        int    `db:"id" json:"id"`
	JobID     int    `db:"job_id" json:"job_id"`
	Name      string `db:"name" json:"name"`
	TemplType string `db:"templ_type" json:"templ_type"`
	TemplID   int    `db:"templ_id" json:"templ_id"`
	Status    string `db:"status" json:"status"`
}

type Tmstmpl struct {
	ID          int    `db:"id" json:"id"`
	StepID      int    `db:"step_id" json:"step_id"`
	TmsConfigID int    `db:"tms_config_id" json:"tms_config_id"`
	TmsNodeID   int    `db:"tms_node_id" json:"tms_node_id"`
	TmsTrIds    []int  `db:"tms_tr_ids" json:"tms_tr_ids"`
	Status      string `db:"status" json:"status"`
}

type User struct {
	ID                int       `db:"id" json:"id"`
	Username          string    `db:"username" json:"username"`
	HashedPassword    string    `db:"hashed_password" json:"hashed_password"`
	FullName          string    `db:"full_name" json:"full_name"`
	Email             string    `db:"email" json:"email"`
	PasswordChangedAt time.Time `db:"password_changed_at" json:"password_changed_at"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
}
