// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO config (
  config_name,
  auth_url,
  api_url,
  auth_client_id,
  auth_client_secret
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, config_name, type, auth_url, api_url, auth_client_id, auth_client_secret
`

type CreateConfigParams struct {
	ConfigName       string `db:"config_name" json:"config_name"`
	AuthUrl          string `db:"auth_url" json:"auth_url"`
	ApiUrl           string `db:"api_url" json:"api_url"`
	AuthClientID     string `db:"auth_client_id" json:"auth_client_id"`
	AuthClientSecret string `db:"auth_client_secret" json:"auth_client_secret"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	row := q.db.QueryRow(ctx, createConfig,
		arg.ConfigName,
		arg.AuthUrl,
		arg.ApiUrl,
		arg.AuthClientID,
		arg.AuthClientSecret,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.Type,
		&i.AuthUrl,
		&i.ApiUrl,
		&i.AuthClientID,
		&i.AuthClientSecret,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
  group_name
) VALUES (
  $1
) RETURNING id, group_name
`

func (q *Queries) CreateGroup(ctx context.Context, groupName string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, groupName)
	var i Group
	err := row.Scan(&i.ID, &i.GroupName)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashed_password,
  full_name,
  email
) VALUES (
  $1, $2, $3, $4
) RETURNING id, username, hashed_password, full_name, email, password_changed_at, created_at
`

type CreateUserParams struct {
	Username       string `db:"username" json:"username"`
	HashedPassword string `db:"hashed_password" json:"hashed_password"`
	FullName       string `db:"full_name" json:"full_name"`
	Email          string `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT id, config_name, type, auth_url, api_url, auth_client_id, auth_client_secret FROM config
WHERE config_name = $1 LIMIT 1
`

func (q *Queries) GetConfig(ctx context.Context, configName string) (Config, error) {
	row := q.db.QueryRow(ctx, getConfig, configName)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.Type,
		&i.AuthUrl,
		&i.ApiUrl,
		&i.AuthClientID,
		&i.AuthClientSecret,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, group_name FROM groups
WHERE group_name = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, groupName string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, groupName)
	var i Group
	err := row.Scan(&i.ID, &i.GroupName)
	return i, err
}

const getGroups = `-- name: GetGroups :many
SELECT id, group_name FROM groups
ORDER BY group_name
`

func (q *Queries) GetGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.GroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, full_name, email, password_changed_at, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, hashed_password, full_name, email, password_changed_at, created_at FROM users
ORDER BY username
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.FullName,
			&i.Email,
			&i.PasswordChangedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
