// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO job (
  name,
  description,
  status,
  type,
  created_by
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, type, description, status, created_at, created_by, modified_at, modified_by
`

type CreateJobParams struct {
	Name        pgtype.Text `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Status      string      `db:"status" json:"status"`
	Type        string      `db:"type" json:"type"`
	CreatedBy   pgtype.Text `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Type,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ModifiedAt,
		&i.ModifiedBy,
	)
	return i, err
}

const deleteDeployStepById = `-- name: DeleteDeployStepById :exec
DELETE FROM deploy_step
WHERE id=$1
`

func (q *Queries) DeleteDeployStepById(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteDeployStepById, id)
	return err
}

const deleteDeployStepByJobId = `-- name: DeleteDeployStepByJobId :exec
DELETE FROM deploy_step
WHERE job_id=$1
`

func (q *Queries) DeleteDeployStepByJobId(ctx context.Context, jobID int) error {
	_, err := q.db.Exec(ctx, deleteDeployStepByJobId, jobID)
	return err
}

const deleteImportStepById = `-- name: DeleteImportStepById :exec
DELETE FROM import_step
WHERE id=$1
`

func (q *Queries) DeleteImportStepById(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteImportStepById, id)
	return err
}

const deleteImportStepByJobId = `-- name: DeleteImportStepByJobId :exec
DELETE FROM import_step
WHERE job_id=$1
`

func (q *Queries) DeleteImportStepByJobId(ctx context.Context, jobID int) error {
	_, err := q.db.Exec(ctx, deleteImportStepByJobId, jobID)
	return err
}

const deleteJobByID = `-- name: DeleteJobByID :one
DELETE FROM job
WHERE id = $1 RETURNING id, name, type, description, status, created_at, created_by, modified_at, modified_by
`

func (q *Queries) DeleteJobByID(ctx context.Context, id int) (Job, error) {
	row := q.db.QueryRow(ctx, deleteJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ModifiedAt,
		&i.ModifiedBy,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, name, type, description, status, created_at, created_by, modified_at, modified_by FROM job
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id int) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ModifiedAt,
		&i.ModifiedBy,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, name, type, description, status, created_at, created_by, modified_at, modified_by FROM job
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ModifiedAt,
			&i.ModifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByType = `-- name: GetJobsByType :many
SELECT id, name, type, description, status, created_at, created_by, modified_at, modified_by FROM job WHERE type=$1
`

func (q *Queries) GetJobsByType(ctx context.Context, type_ string) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ModifiedAt,
			&i.ModifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeployStep = `-- name: InsertDeployStep :one
INSERT INTO deploy_step (
  job_id,
  status,
  sequence,
  endpoint,
  package_id,
  artifact_ids
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, job_id, sequence, status, endpoint, package_id, artifact_ids
`

type InsertDeployStepParams struct {
	JobID       int      `db:"job_id" json:"job_id"`
	Status      string   `db:"status" json:"status"`
	Sequence    int      `db:"sequence" json:"sequence"`
	Endpoint    string   `db:"endpoint" json:"endpoint"`
	PackageID   string   `db:"package_id" json:"package_id"`
	ArtifactIds []string `db:"artifact_ids" json:"artifact_ids"`
}

func (q *Queries) InsertDeployStep(ctx context.Context, arg InsertDeployStepParams) (DeployStep, error) {
	row := q.db.QueryRow(ctx, insertDeployStep,
		arg.JobID,
		arg.Status,
		arg.Sequence,
		arg.Endpoint,
		arg.PackageID,
		arg.ArtifactIds,
	)
	var i DeployStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.Endpoint,
		&i.PackageID,
		&i.ArtifactIds,
	)
	return i, err
}

const insertImportStep = `-- name: InsertImportStep :one
INSERT INTO import_step (
  job_id,
  status,
  sequence,
  transport_node_id,
  transport_node_name,
  transport_requests
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, job_id, sequence, status, transport_node_id, transport_node_name, transport_requests
`

type InsertImportStepParams struct {
	JobID             int    `db:"job_id" json:"job_id"`
	Status            string `db:"status" json:"status"`
	Sequence          int    `db:"sequence" json:"sequence"`
	TransportNodeID   int    `db:"transport_node_id" json:"transport_node_id"`
	TransportNodeName string `db:"transport_node_name" json:"transport_node_name"`
	TransportRequests []int  `db:"transport_requests" json:"transport_requests"`
}

func (q *Queries) InsertImportStep(ctx context.Context, arg InsertImportStepParams) (ImportStep, error) {
	row := q.db.QueryRow(ctx, insertImportStep,
		arg.JobID,
		arg.Status,
		arg.Sequence,
		arg.TransportNodeID,
		arg.TransportNodeName,
		arg.TransportRequests,
	)
	var i ImportStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.TransportNodeID,
		&i.TransportNodeName,
		&i.TransportRequests,
	)
	return i, err
}

const selectDeployStepsByJobId = `-- name: SelectDeployStepsByJobId :many
SELECT id, job_id, sequence, status, endpoint, package_id, artifact_ids FROM deploy_step WHERE job_id=$1
`

func (q *Queries) SelectDeployStepsByJobId(ctx context.Context, jobID int) ([]DeployStep, error) {
	rows, err := q.db.Query(ctx, selectDeployStepsByJobId, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployStep{}
	for rows.Next() {
		var i DeployStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.Endpoint,
			&i.PackageID,
			&i.ArtifactIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectImportStepsByJobId = `-- name: SelectImportStepsByJobId :many
SELECT id, job_id, sequence, status, transport_node_id, transport_node_name, transport_requests From import_step WHERE job_id=$1
`

func (q *Queries) SelectImportStepsByJobId(ctx context.Context, jobID int) ([]ImportStep, error) {
	rows, err := q.db.Query(ctx, selectImportStepsByJobId, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportStep{}
	for rows.Next() {
		var i ImportStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Sequence,
			&i.Status,
			&i.TransportNodeID,
			&i.TransportNodeName,
			&i.TransportRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployStep = `-- name: UpdateDeployStep :one
UPDATE deploy_step
SET status=$2, endpoint=$3, sequence=$4, package_id=$5, artifact_ids=$6
WHERE id=$1 RETURNING id, job_id, sequence, status, endpoint, package_id, artifact_ids
`

type UpdateDeployStepParams struct {
	ID          int      `db:"id" json:"id"`
	Status      string   `db:"status" json:"status"`
	Endpoint    string   `db:"endpoint" json:"endpoint"`
	Sequence    int      `db:"sequence" json:"sequence"`
	PackageID   string   `db:"package_id" json:"package_id"`
	ArtifactIds []string `db:"artifact_ids" json:"artifact_ids"`
}

func (q *Queries) UpdateDeployStep(ctx context.Context, arg UpdateDeployStepParams) (DeployStep, error) {
	row := q.db.QueryRow(ctx, updateDeployStep,
		arg.ID,
		arg.Status,
		arg.Endpoint,
		arg.Sequence,
		arg.PackageID,
		arg.ArtifactIds,
	)
	var i DeployStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.Endpoint,
		&i.PackageID,
		&i.ArtifactIds,
	)
	return i, err
}

const updateImportStep = `-- name: UpdateImportStep :one
UPDATE import_step
SET status=$2, sequence=$3, transport_node_id=$4, transport_node_name=$5, transport_requests=$6
WHERE id=$1 RETURNING id, job_id, sequence, status, transport_node_id, transport_node_name, transport_requests
`

type UpdateImportStepParams struct {
	ID                int    `db:"id" json:"id"`
	Status            string `db:"status" json:"status"`
	Sequence          int    `db:"sequence" json:"sequence"`
	TransportNodeID   int    `db:"transport_node_id" json:"transport_node_id"`
	TransportNodeName string `db:"transport_node_name" json:"transport_node_name"`
	TransportRequests []int  `db:"transport_requests" json:"transport_requests"`
}

func (q *Queries) UpdateImportStep(ctx context.Context, arg UpdateImportStepParams) (ImportStep, error) {
	row := q.db.QueryRow(ctx, updateImportStep,
		arg.ID,
		arg.Status,
		arg.Sequence,
		arg.TransportNodeID,
		arg.TransportNodeName,
		arg.TransportRequests,
	)
	var i ImportStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Sequence,
		&i.Status,
		&i.TransportNodeID,
		&i.TransportNodeName,
		&i.TransportRequests,
	)
	return i, err
}

const updateJobByID = `-- name: UpdateJobByID :one
UPDATE job
SET 
  name=$2, 
  description=$3, 
  status=$4, 
  modified_at=$5, 
  modified_by=$6
WHERE id=$1 RETURNING id, name, type, description, status, created_at, created_by, modified_at, modified_by
`

type UpdateJobByIDParams struct {
	ID          int                `db:"id" json:"id"`
	Name        pgtype.Text        `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Status      string             `db:"status" json:"status"`
	ModifiedAt  pgtype.Timestamptz `db:"modified_at" json:"modified_at"`
	ModifiedBy  pgtype.Text        `db:"modified_by" json:"modified_by"`
}

func (q *Queries) UpdateJobByID(ctx context.Context, arg UpdateJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobByID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ModifiedAt,
		arg.ModifiedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ModifiedAt,
		&i.ModifiedBy,
	)
	return i, err
}
