###
Get http://127.0.0.1:9000

###
Get http://127.0.0.1:9000/api/v1/apiEndpoint

###
POST http://127.0.0.1:9000/api/v1/apiEndpoint

{
    "name": "CPI dev",
    "type":"CPI",
    "authUrl":"https://mmt-test-hfc.authentication.eu10.hana.ondemand.com/oauth/token",
    "apiUrl":"https://mmt-test-hfc.it-cpi026.cfapps.eu10-002.hana.ondemand.com",
    "clientId":"sb-8f42f318-747c-4aa1-9da7-d54287569114!b443441|it!b410603",
    "clientSecret":"REDACTED"
}

###
POST http://127.0.0.1:9000/api/v1/apiEndpoint

{
    "name": "TMS devops",
    "type":"TMS",
    "description": "???",
    "authUrl":"https://stage-devops.authentication.sap.hana.ondemand.com/oauth/token",
    "apiUrl":"https://transport-service-app-backend.ts.cfapps.sap.hana.ondemand.com/v2",
    "clientId":"sb-9db92843-8155-437e-a5d9-d84ac1cfc5d7!b14446|alm-ts-backend!b339",
    "clientSecret":"REDACTED"
}

###
GET http://127.0.0.1:9000/api/v1/tanant/packages?tenant=4

###
GET http://127.0.0.1:9000/api/v1/tenant/packages/iflows?tenant=4&package=SAPMaCoforUtilitiesEmailProcessingV4


### 
GET http://127.0.0.1:9000/api/v1/tms/nodes?tenant=3


###
POST http://127.0.0.1:9000/api/v1/importStep

{
    "job_id": 0,
    "status": "initial",
    "sequence": 2,
    "endpoint_id": 3,
    "transport_node": 10,
    "transport_requests": [10,312,33,8960]
}

###
POST http://127.0.0.1:9000/api/v1/deployStep

{
    "job_id": 0,
    "status": "initial",
    "sequence": 3,
    "endpoint_id": 3,
    "package_id": 10,
    "artifact_ids": [11,3234,12331,4423]
}

###
GET http://127.0.0.1:9000/api/v1/steps/0

###
POST http://127.0.0.1:9000/api/v1/job

{
    "name": "Job 01",
    "steps": []
}

###
GET http://127.0.0.1:9000/api/v1/job/3

###
DELETE http://127.0.0.1:9000/api/v1/job/4


###
GET  http://127.0.0.1:9000/api/v1/destinations

###
GET http://127.0.0.1:8080/api/v1/userInfo


###
GET http://127.0.0.1:8080/api/v1/job/Deploy